apiVersion: v1
kind: Service
metadata:
  name: broker-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    app: broker
  ports:
    - port: 10000
      targetPort: 10000
      nodePort: 31000
  externalTrafficPolicy: Cluster