apiVersion: apps/v1
kind: Deployment
metadata:
  name: multmatrix
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: multmatrix
  template:
    metadata:
      labels:
        app: multmatrix
    spec:
      nodeSelector:
        name: multmatrix
      containers:
        - name: kubernetes-multmatrix
          image: docker.io/adriitoral/practica2:172.31.92.183
          command: [ "sh", "/loader.sh", "mm_server" ]
          imagePullPolicy: Always